# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Juliana Resplande
title: NLP Engineer
email: julianarsg13@gmail.com
website: https://ju-resplande.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username: ju-resplande
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: juliana-resplande
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0001-6900-1931

# Additional icon links
additional_links:
  - title: ResearchGAte
    icon: images/researchgate.png
    url: https://www.researchgate.net/profile/Juliana-Resplande
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: https://avatars.githubusercontent.com/u/28462295?v=4
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Juliana and I'm a NLP engineer.
  My research interests are Portuguese Corpora, Question Answering Systems, and Knowledge Graphs.

  I skilled in: <mark>Python</mark>, <mark>Bash</mark>, <mark>Pandas</mark>,<mark>Elasticsearch</mark>, <mark>Docker</mark> and <mark>FastAPI</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Federal University of Goiás
        caption: 2017 - 2011
        sub_title: BSc Computer Science
        quote: >
          GPA: 3.6/4.0
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Intelligent Assistant for Monitoring Continuous Medical Care for Chronic Patient
        caption: 2021 - 2022
        quote: >
          Information Retrieval in common health question answering pipeline.
      - layout: top-middle
        title: Development of an Intelligent Assistant for the Copel Holding Shared Services Center
        caption: 2020 - 2021
        quote: >
          Development of intent classification modules
      - layout: top-middle
        title: Application of Machine Learning Techniques and Corpus Linguistics in Portuguese
        caption: 2020 - 2020
        quote: >
          Corpora automatic translation to Brazilian Portuguese.
      - layout: top-middle
        title: Multi-Tasking Deep Neural Networks in Portuguese
        caption: 2019 - 2020
        quote: >
          Multitasking architecture employment for Natural Language Understanding Portuguese Tasks.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mr. Turing
        link: https://misterturing.com/
        # link_text: boringcompany.com
        sub_title: NLP engineer
        caption: January 2021 - Present
        quote: >
          Development NLP modules to attend business needs.
        description: | # this will include new lines to allow paragraphs
          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: left
        title: Centro de Excelência em Inteligência Artificial (CEIA)
        link: https://www.inf.ufg.br/p/39527-centro-de-excelencia-em-inteligencia-artificial-ceia
        # link_text: boringcompany.com
        sub_title: NLP researcher
        caption: January 2020 - Present
        quote: >
          Researcher in various projects.

  - title: Honour # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ABSAPT 2022
        caption: 2022
        sub_title: 1st place
        description: | # this will include new lines to allow paragraphs
          Aspect-Based Sentiment Analysis in Portuguese, first shared task dedicated to identify aspects and extract the polarity in texts written in Portuguese. This task was part of IberLEF 2022.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in NLP engineering some of my other interests and hobbies are:
      - Running
      - Rock climbing
      - Board Games
      - Puzzles

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
